#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : NetworkManager-openconnect
Version  : 1.2.6
Release  : 8
URL      : https://download.gnome.org/sources/NetworkManager-openconnect/1.2/NetworkManager-openconnect-1.2.6.tar.xz
Source0  : https://download.gnome.org/sources/NetworkManager-openconnect/1.2/NetworkManager-openconnect-1.2.6.tar.xz
Summary  : NetworkManager VPN plugin for OpenConnect
Group    : Development/Tools
License  : GPL-2.0
Requires: NetworkManager-openconnect-data = %{version}-%{release}
Requires: NetworkManager-openconnect-lib = %{version}-%{release}
Requires: NetworkManager-openconnect-libexec = %{version}-%{release}
Requires: NetworkManager-openconnect-license = %{version}-%{release}
Requires: NetworkManager-openconnect-locales = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-gnome
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : intltool
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(NetworkManager)
BuildRequires : pkgconfig(gcr-3)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libnm)
BuildRequires : pkgconfig(libnm-glib)
BuildRequires : pkgconfig(libnm-glib-vpn)
BuildRequires : pkgconfig(libnm-util)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(openconnect)
Patch1: 0001-Use-stateless-vendor-d-bus-directory.patch

%description
OpenConnect VPN client
Support for configuring SSL VPN virtual private network connections using OpenConnect.
Compatible with Cisco AnyConnect, Juniper and ocserv based networks.

%package data
Summary: data components for the NetworkManager-openconnect package.
Group: Data

%description data
data components for the NetworkManager-openconnect package.


%package lib
Summary: lib components for the NetworkManager-openconnect package.
Group: Libraries
Requires: NetworkManager-openconnect-data = %{version}-%{release}
Requires: NetworkManager-openconnect-libexec = %{version}-%{release}
Requires: NetworkManager-openconnect-license = %{version}-%{release}

%description lib
lib components for the NetworkManager-openconnect package.


%package libexec
Summary: libexec components for the NetworkManager-openconnect package.
Group: Default
Requires: NetworkManager-openconnect-license = %{version}-%{release}

%description libexec
libexec components for the NetworkManager-openconnect package.


%package license
Summary: license components for the NetworkManager-openconnect package.
Group: Default

%description license
license components for the NetworkManager-openconnect package.


%package locales
Summary: locales components for the NetworkManager-openconnect package.
Group: Default

%description locales
locales components for the NetworkManager-openconnect package.


%prep
%setup -q -n NetworkManager-openconnect-1.2.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568045358
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1568045358
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/NetworkManager-openconnect
cp COPYING %{buildroot}/usr/share/package-licenses/NetworkManager-openconnect/COPYING
%make_install
%find_lang NetworkManager-openconnect

%files
%defattr(-,root,root,-)
/usr/lib/NetworkManager/VPN/nm-openconnect-service.name

%files data
%defattr(-,root,root,-)
/usr/share/appdata/network-manager-openconnect.metainfo.xml
/usr/share/dbus-1/system.d/nm-openconnect-service.conf
/usr/share/gnome-vpn-properties/openconnect/nm-openconnect-dialog.ui

%files lib
%defattr(-,root,root,-)
/usr/lib64/NetworkManager/libnm-vpn-plugin-openconnect-editor.so
/usr/lib64/NetworkManager/libnm-vpn-plugin-openconnect.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/nm-openconnect-auth-dialog
/usr/libexec/nm-openconnect-service
/usr/libexec/nm-openconnect-service-openconnect-helper

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/NetworkManager-openconnect/COPYING

%files locales -f NetworkManager-openconnect.lang
%defattr(-,root,root,-)

